spring.application.name=profiler
server.port=${PORT:8080}

#spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${PGUSER}
spring.datasource.password=${POSTGRES_PASSWORD}



spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#Railway usually provides REDIS_URL or REDISHOST/REDISPORT
spring.data.redis.url=${REDIS_PUBLIC_URL}
spring.data.redis.host=${REDISHOST}
spring.data.redis.password=${REDIS_PASSWORD}


spring.security.user.name=profiler
spring.security.user.password=profiler

profiler.security.jwt-secret-key=${JWT_SECRET_KEY}

github.client.id=${GITHUB_CLIENT_ID}
github.client.secret=${GITHUB_CLIENT_SECRET}
github.cli.client.id=${CLI_CLIENT_ID}
github.cli.client.secret=${CLI_CLIENT_SECRET}
github.redirect.uri=https://profiler-api-production.up.railway.app
github.cli.redirect.uri=http://localhost:9095/callback